### ISSUE TITLE
What is the required build environment as of 7/2022?

### ISSUE THREAD

**Issue by gwhizoftv** [michaljaz/webmc#143]
Hi All,

Could we list the crucial build environment requirements somewhere?

I cloned the repo to my MacOS Monterey machine. It seemed that the build required node 14.x so I happened to had 14.17.6 installed. When I try to build with that, I get a lot of errors:

```
Michaels-Mac-Pro:webmc MGW$ nvm use 14
Now using node v14.17.6 (npm v6.14.15)
Michaels-Mac-Pro:webmc MGW$ rm -rf node_modules
Michaels-Mac-Pro:webmc MGW$ ls 
Dockerfile	LICENSE		README.md	assets		docs		index.js	lib		package.json	src
Michaels-Mac-Pro:webmc MGW$ npm i
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> fsevents@1.2.13 install /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/MGW/.nvm/versions/node/v14.17.6/bin/node" "/Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> lzma-native@4.0.6 install /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.6 and node@14.17.6 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/MGW/.nvm/versions/node/v14.17.6/bin/node" "/Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/MGW/.nvm/versions/node/v14.17.6/bin/node /Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/Users/MGW/.nvm/versions/node/v14.17.6/bin/node" "/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/MGW/.nvm/versions/node/v14.17.6/bin/node /Users/MGW/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v83-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN prismarine-biome@1.3.0 requires a peer of minecraft-data@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prismarine-recipe@1.2.0 requires a peer of minecraft-data@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MGW/.npm/_logs/2022-07-23T23_30_17_976Z-debug.log
Michaels-Mac-Pro:webmc MGW$ 
```
I also tried the latest stable node but got other errors about the build working with gyp and node-pre-gyp and trying to use node 16.4.0, despite me telling it to use 18.
```
Michaels-Mac-Pro:webmc MGW$ nvm use stable
Now using node v18.6.0 (npm v8.15.0)
Michaels-Mac-Pro:webmc MGW$ rm -rf node_modules
Michaels-Mac-Pro:webmc MGW$ ls
Dockerfile	README.md	docs		lib		src
LICENSE		assets		index.js	package.json
Michaels-Mac-Pro:webmc MGW$ npm i

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: prismarine-biome@1.3.0
npm WARN Found: minecraft-data@2.221.0
npm WARN node_modules/minecraft-data
npm WARN   minecraft-data@"^2.79.0" from the root project
npm WARN   1 more (mineflayer)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer minecraft-data@"^3.0.0" from prismarine-biome@1.3.0
npm WARN node_modules/prismarine-biome
npm WARN   prismarine-biome@"^1.1.1" from mineflayer@3.18.0
npm WARN   node_modules/mineflayer
npm WARN   2 more (prismarine-block, prismarine-chunk)
npm WARN 
npm WARN Conflicting peer dependency: minecraft-data@3.9.1
npm WARN node_modules/minecraft-data
npm WARN   peer minecraft-data@"^3.0.0" from prismarine-biome@1.3.0
npm WARN   node_modules/prismarine-biome
npm WARN     prismarine-biome@"^1.1.1" from mineflayer@3.18.0
npm WARN     node_modules/mineflayer
npm WARN     2 more (prismarine-block, prismarine-chunk)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: prismarine-recipe@1.2.0
npm WARN Found: minecraft-data@2.221.0
npm WARN node_modules/minecraft-data
npm WARN   minecraft-data@"^2.79.0" from the root project
npm WARN   1 more (mineflayer)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer minecraft-data@"^3.0.0" from prismarine-recipe@1.2.0
npm WARN node_modules/prismarine-recipe
npm WARN   prismarine-recipe@"^1.1.0" from mineflayer@3.18.0
npm WARN   node_modules/mineflayer
npm WARN 
npm WARN Conflicting peer dependency: minecraft-data@3.9.1
npm WARN node_modules/minecraft-data
npm WARN   peer minecraft-data@"^3.0.0" from prismarine-recipe@1.2.0
npm WARN   node_modules/prismarine-recipe
npm WARN     prismarine-recipe@"^1.1.0" from mineflayer@3.18.0
npm WARN     node_modules/mineflayer
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'webmc@1.0.0',
npm WARN EBADENGINE   required: { node: '14.x' },
npm WARN EBADENGINE   current: { node: 'v18.6.0', npm: '8.15.0' }
npm WARN EBADENGINE }
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
npm ERR! command failed
npm ERR! command sh /var/folders/h_/19b941jn5x140n94lxr4flkc0000gn/T/install-4cb0aeb0.sh
npm ERR! ACTION binding_gyp_liblzma_target_build .
npm ERR! Failed to execute '/Users/MGW/node_modules/node/bin/node /Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@16.4.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64/lzma_native.node" (not found)
npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for lzma-native@4.0.6 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-darwin-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.4.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.4.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/MGW/Library/Caches/node-gyp/16.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/MGW/Library/Caches/node-gyp/16.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/MGW/Library/Caches/node-gyp/16.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.4.0 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: -c: line 0: syntax error near unexpected token `('
npm ERR! /bin/sh: -c: line 0: `LD_LIBRARY_PATH=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/build/Release/lib.host:/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh "/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/liblzma-build.sh" "/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/build"'
npm ERR! make: *** [.] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/Users/MGW/node_modules/node/bin/node" "/Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
npm ERR! gyp ERR! node -v v16.4.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/MGW/node_modules/node/bin/node /Users/MGW/.nvm/versions/node/v18.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native/binding-v4.0.6-node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.5.0
npm ERR! node-pre-gyp ERR! command "/Users/MGW/node_modules/node/bin/node" "/Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/MGW/Dropbox (TotalVU)/Smart Blonde Experiential/BITBUCKET-REPOS/webmc/webmc/node_modules/lzma-native
npm ERR! node-pre-gyp ERR! node -v v16.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MGW/.npm/_logs/2022-07-23T23_39_45_070Z-debug-0.log
Michaels-Mac-Pro:webmc MGW$ 
Michaels-Mac-Pro:webmc MGW$ node -v
v18.6.0
Michaels-Mac-Pro:webmc MGW$ 
Michaels-Mac-Pro:webmc MGW$ ls
Dockerfile	README.md	docs		lib		src
LICENSE		assets		index.js	package.json
```

**Comment by michaljaz** [comment]
node 14.17.0 should work
also you can try with docker
