### ISSUE TITLE
Latest Dockerfile does not work

### ISSUE THREAD

**Issue by Ratizux** [michaljaz/webmc#155]
I'm using Podman 3.0.1 on Debian 11(`5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`) with latest Dockerfile, but encountered the following error:

```
> webmc@1.0.0 start /usr/src/app
> npm run prebuild && node index.js

> webmc@1.0.0 prebuild /usr/src/app
> node lib/prebuild.js

/usr/src/app/assets/pack/assets/minecraft/models/block
/usr/src/app/assets/pack/assets/minecraft/blockstates
Block max stateId: 17111
Generated blocksDefinitions: /usr/src/app/src/assets/blocks/blocksDef.json

/usr/src/app/lib/merger.js:10
    files.forEach((file) => {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/src/app/lib/merger.js:10:11
    at FSReqCallback.oncomplete (fs.js:180:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webmc@1.0.0 prebuild: `node lib/prebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webmc@1.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-19T03_34_49_195Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webmc@1.0.0 start: `npm run prebuild && node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webmc@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-19T03_34_49_289Z-debug.log
```

[2023-02-19T03_34_49_195Z-debug.log](https://github.com/michaljaz/webmc/files/10776040/2023-02-19T03_34_49_195Z-debug.log)

[2023-02-19T03_34_49_289Z-debug.log](https://github.com/michaljaz/webmc/files/10776041/2023-02-19T03_34_49_289Z-debug.log)

I feel it necessary to mention that switching node version to 12 or 13 in Dockerfile can not fix this, but manual installation on Debian 11 container (with node v12.22.12) works.

**Comment by michaljaz** [comment]
is working for me ;)
